- name: Enable spine leaf-facing interfaces (L3 ports toward leafs)
  nokia.srlinux.config:
    update:
      - path: "/interface[name=ethernet-1/{{ item }}]"
        value:
          name: "ethernet-1/{{ item }}"
          admin-state: enable
          subinterface:
            - index: 1
              ipv6:
                admin-state: enable
                router-advertisement:
                  router-role:
                    admin-state: enable
  loop: "{{ range(1, leaf_count + 1) | list }}"

- name: Configure default network instance (BGP on spine)
  nokia.srlinux.config:
    replace:
      - path: "/network-instance[name=default]"
        value: "{{ lookup('ansible.builtin.template', 'roles/spine/templates/spine_network_instance.json.j2') }}"

- name: Configure spine loopback interface (system0)
  nokia.srlinux.config:
    update:
      - path: "/interface[name=system0]"
        value:
          name: "system0"
          subinterface:
            - index: 0
              ipv4:
                admin-state: enable
                address:
                  - ip-prefix: "{{ loopback_ip }}"
